-- AlterTable
ALTER TABLE "users" ALTER COLUMN "avatar_url" DROP DEFAULT,
ALTER COLUMN "bio" DROP DEFAULT,
ALTER COLUMN "github_url" DROP DEFAULT,
ALTER COLUMN "linkedin_url" DROP DEFAULT,
ALTER COLUMN "last_name" DROP DEFAULT;
